//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerProUtil {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class CareerProUtil : global::System.Configuration.ApplicationSettingsBase {
        
        private static CareerProUtil defaultInstance = ((CareerProUtil)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CareerProUtil())));
        
        public static CareerProUtil Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\user\\docs")]
        public string InputLocation {
            get {
                return ((string)(this["InputLocation"]));
            }
            set {
                this["InputLocation"] = value;
            }
        }
    }
}
